version: '3'
#backend
services:
  backend:
    build:
      context: ./modulo5
    container_name: backend 
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
#Frontend 
  storybook:
    ports:
      - "6006:6006"
    build: 
      context: ./reactapp
    container_name: frontend
    depends_on:
      - backend 
